### Получить всех пользователей
GET http://localhost:3000/users

### возвращает пользователя по ID
GET http://localhost:3000/users/638a18e5564e527e4b5bd598


### Создает пользователя
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "",
  "about": "awdawdawd",
  "avatar": "https://ya.ru/av.bmp"
}

### Обновить данные пользователя
PATCH http://localhost:3000/users/me
Content-Type: application/json

{
  "name": "Дима",
  "about": "Программист ПИТОН"
}

### Обновить Аватар пользователя
PATCH http://localhost:3000/users/me/avatar
Content-Type: application/json

{
  "avatar": "https://images.unsplash.com/photo-1670431757843-e8fd3f24490f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHw0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=700&q=60"
}






### получить все карточки
GET http://localhost:3000/cards

### создает карточку
POST http://localhost:3000/cards
Content-Type: application/json

{
  "name": "123465666123вфцфвцфвцвфцв",
  "link": "https://images.unsplash.com/photo-1670070633288-72a46e449866?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwzfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=900&q=60",
  "owner": "638a18e5564e527e4b5bd599"
}

### удаляет карточку по id
DELETE http://localhost:3000/cards/6391b7291c512bd4c2de3ef1

### поставить лайк на карточку
PUT http://localhost:3000/cards/6392338ea669a3d2319ef3d2/likes

### убрать лайк с карточки
DELETE http://localhost:3000/cards/6392338ea669a3d2319ef3d3/likes


